///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest75
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest75Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1a0eebac-452e-4af9-9568-ccd35bf92f1f")]
    public partial class MyTest75Repository : RepoGenBaseFolder
    {
        static MyTest75Repository instance = new MyTest75Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest75Repository element repository.
        /// </summary>
        [RepositoryFolder("1a0eebac-452e-4af9-9568-ccd35bf92f1f")]
        public static MyTest75Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest75Repository() 
            : base("MyTest75Repository", "/", null, 0, false, "1a0eebac-452e-4af9-9568-ccd35bf92f1f", ".\\RepositoryImages\\MyTest75Repository1a0eebac.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1a0eebac-452e-4af9-9568-ccd35bf92f1f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest75RepositoryFolders
    {
    }
#pragma warning restore 0436
}
